apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: digi
  name: prom-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-lab
  template:
    metadata:
      labels:
        app: prom-lab
      annotations:
        ad.datadoghq.com/prom-lab.checks: |
          {
            "istio": {
              "ad_identifiers": ["proxyv2"],
              "instances": [
                {
                  "istio_mesh_endpoint": "http://%%host%%:15020/stats/prometheus",
                  "use_openmetrics": true,
                  "namespace": "toy",
                  "histogram_buckets_as_distributions": true
                }
              ]
            },
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:%%port%%/metrics",
                  "namespace": "toy",
                  "metrics": [".*"]
                }
              ]
            }
          }    
    spec:
      containers:
        - name: prom-lab
          imagePullPolicy: Always
          image: yoavklein3/python-http-server:0.1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: prom-lab
  namespace: digi
spec:
  selector:
    app: prom-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
