apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: digi
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        ad.datadoghq.com/server.checks: |
          {
            "istio": {
              "ad_identifiers": ["proxyv2"],
              "instances": [
                {
                  "istio_mesh_endpoint": "http://%%host%%:15020/stats/prometheus",
                  "use_openmetrics": true,
                  "namespace": "yoav",
                  "histogram_buckets_as_distributions": true
                }
              ]
            }
          }    
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: yoavklein3/python-http-server:0.1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: digi
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
